Feat: CLI `polywrap codegen` Command (plugin & app projects)
Web3-API/prototype pull request #1051
Opened 2022-07-16 11:28 UTC by dOrgJelli

I think the CLI interface should be:
```
polywrap codegen
polywrap build
polywrap deploy
polywrap infra
polywrap create
polywrap run
```

Where each command decides internally what projects it works with.

This PR consolidates the `polywrap plugin codegen` and `polywrap app codegen` commands into a single `polywrap codegen` command. Additionally it refines best-practices about what options should be defined in polywrap manifest files and which are provided on the CLI.

NOTE: see the `todo` file for WIP impl notes

2022-09-02 17:06 UTC, pileks commented
`polywrap codegen` is now the **only** `codegen` command in the CLI right now. 😄 

@dorgjelli it seems that `codegen` outputs into `./src/wrap` for all project types currently, so I have kept it at that.

Work that should be split into issues and done separately:

- [ ] `codegen` for plugins appears to also output the plugins ABI into a `./build` folder. We should refactor this out into the `polywrap build` command, and extend the `build` command to support plugins as well.
  - This would also move the `--publish-dir` option that the plugin `codegen` uses into `build`'s `--output-dir` option
  - `codegen` would then support `wasm`, `plugin` and `app` project types, while `build` would support `wasm`, `plugin` and `interface` types
- [ ] move `--codegen-dir`, `--publish-dir`, and `--client-config` into manifest files. Separate tasks for each of those might seem fair.
    - [ ] `--codegen-dir` issue created
    - [ ] `--publish-dir` issue created
    - [ ] `--client-config` issue created

2022-09-02 17:51 UTC, pileks commented
> * [ ]  move `--codegen-dir`, `--publish-dir`, and `--client-config` into manifest files. Separate tasks for each of those might seem fair.
>   
>   * [ ]  `--codegen-dir` issue created
>   * [ ]  `--publish-dir` issue created
>   * [ ]  `--client-config` issue created

Note: we should probably rethink our manifest migration strategy before messing with manifests. While we can have all of these options set as optional manifest properties, I'd say that we'll likely want to create a proper migration strategy sooner than later, as it will reduce future work.

Current migration strategy:
Auto-generated code requires us to implement certain, fixed migrators.
```
available manifests:
0.1.0
0.2.0
0.3.0
0.4.0

migrators/migration paths:
0.1.0 -> 0.4.0
0.2.0 -> 0.4.0
0.3.0 -> 0.4.0
```

Proposed migration strategy:
Allow developers to declare their own migrators, from whichever version to whichever other version.
A simple search algorithm would then find the appropriate migration path, and could even allow for downgrades if the correct migrator exists.

```
available manifests:
0.1.0
0.2.0
0.3.0

migrators:
0.1.0 -> 0.2.0
0.2.0 -> 0.3.0
0.3.0 -> 0.4.0
0.1.0 -> 0.3.0

migration paths to 0.4.0:
0.1.0 -> 0.2.0 -> 0.3.0 -> 0.4.0
0.1.0 -> 0.3.0 -> 0.4.0
```

2022-09-02 18:17 UTC, pileks commented
Added feature for the splitting of plugin `codegen` behavior:
https://github.com/polywrap/toolchain/issues/1210

2022-09-05 08:56 UTC, krisbitney requested changes
This PR is awesome. I think it's a very positive change. Thanks for working on this.

I'm concerned about the maintainability of `getProjectFromManifest.ts`. I refactored some it in another branch so you can see what I'm thinking. I messaged you.

2022-09-05 08:56 UTC, krisbitney commented on packages/cli/src/lib/project/helpers/getProjectFromManifest.ts
> +  switch (format) {
I think the methods in this file are too prone to breaking

2022-09-05 08:56 UTC, krisbitney commented on packages/interfaces/file-system/package.json
> +  "version": "0.4.1",
Are the interfaces breaking at version 0.6.0?

2022-09-05 15:15 UTC, pileks commented on packages/cli/src/lib/project/helpers/getProjectFromManifest.ts
> +  switch (format) {
Can agree.
As an aside, we've decided to go with your refactor, as it's something that I've also done before going with this complicated approach. If 2 devs blindly do it, it's surely worth something 😁

2022-09-05 15:17 UTC, pileks commented on packages/interfaces/file-system/package.json
> +  "version": "0.4.1",
This is just a happy little accident 😄

2022-09-06 05:26 UTC, krisbitney approved these changes, later dismissed

2022-09-06 05:28 UTC, krisbitney commented
The dependencies in the other interfaces were also changed to 0.4.1

2022-09-07 03:45 UTC, krisbitney approved these changes

2022-09-07 03:47 UTC, dOrgJelli reviewed
Awesome work @pileks!

2022-09-07 03:53 UTC, merged