Python Client Implementation
Web3-API/prototype pull request #1093
Opened 2022-08-03 15:53 UTC by dOrgJelli

2022-08-04 14:00 UTC, Niraj-Kamdar requested changes
I have left some QA + improvement comments. Please check it out. 

Feel free to ignore my origin todo comments

2022-08-04 14:00 UTC, Niraj-Kamdar commented on packages/py/core/src/algorithms/apply_redirects.py
> +        serialize_message = {}
Annotate types wherever possible to make it easy to read the code

2022-08-04 14:00 UTC, Niraj-Kamdar commented on packages/py/core/src/algorithms/combine_paths.py
> +    a = a.replace("/\\/g", "/")
How about using path object from pathlib instead? 
https://docs.python.org/3/library/pathlib.html

2022-08-04 14:00 UTC, Niraj-Kamdar commented on packages/py/core/src/algorithms/find_plugin_package.py
> +    plugin_redirect = next(filter(lambda x: Uri.equals(x.uri, uri), plugins), None)
We should use Pythonic operator overloading instead of custom methods. add `__eq__` method to Uri class

2022-08-04 14:00 UTC, Niraj-Kamdar commented on packages/py/core/src/algorithms/get_implementations.py
> +    api_interface_uri: Uri, interfaces: List[InterfaceImplementations], redirects=None
redirects type should be `Optional[List[UriRedirect]]`

2022-08-04 14:00 UTC, Niraj-Kamdar commented on packages/py/core/src/algorithms/filter_results.py
> +
TODO: remove this file since not needed after origin

2022-08-04 14:00 UTC, Niraj-Kamdar commented on packages/py/core/src/types/client.py
> +class Client:
Shouldn't this be an abstract class?

2022-08-04 14:00 UTC, Niraj-Kamdar commented on packages/py/core/src/types/client.py
> +        return
Use pass or docstrings instead of return

2022-08-04 14:00 UTC, Niraj-Kamdar commented on packages/py/core/src/types/env.py
> +
We shouldn't use docstrings like this. Let's use a standard docstring format like: Google, numpy, or reST, Epytext, etc

2022-08-04 14:00 UTC, Niraj-Kamdar commented on packages/py/core/src/types/maybe_async.py
> +    return test and inspect.iscoroutine(test)
there isn't anything like promise in python so let's use terminology that pythonista uses (i.e. coroutine).

2022-08-04 14:00 UTC, Niraj-Kamdar commented on packages/py/core/src/types/query.py
> +        return
No need to have return

2022-08-04 14:00 UTC, Niraj-Kamdar commented on packages/py/core/src/types/subscriptions.py
> +    ms: int = None
This is Optional[int] type not an int

2022-08-04 14:00 UTC, Niraj-Kamdar commented on packages/py/core/src/types/subscriptions.py
> +        Subscription
This should be return type and function body should just have pass

2022-08-04 14:00 UTC, Niraj-Kamdar commented on packages/py/core/src/uri_resolution/core/resolve_uri.py
> +                print('inf loop')
Is it debug leftover?

2022-08-04 14:00 UTC, Niraj-Kamdar commented on packages/py/core/src/uri_resolution/core/types/uri_resolution_history.py
> +    def get_resolution_path(self) -> "UriResolutionHistory":
Is it a typo? `UriResolutionHistory` should be a type right?

2022-08-04 14:00 UTC, Niraj-Kamdar commented on packages/py/core/src/uri_resolution/core/types/uri_resolution_result.py
> +    api: "Api" = None
Fix typing

2022-08-04 14:00 UTC, Niraj-Kamdar commented on packages/py/core/src/uri_resolution/core/types/uri_resolution_stack.py
> +UriResolutionStack: List[UriResolutionInfo] = list()
just define this as type annotation

2022-08-04 14:00 UTC, Niraj-Kamdar commented on packages/py/core/src/uri_resolution/resolvers/extendable/extendable_uri_resolvers.py
> +                    return {"success": False, "failed_uri_resolvers": list(x.uri for x in implementations_to_load)}
```suggest
                    return {"success": False, "failed_uri_resolvers": [x.uri for x in implementations_to_load]}
```

2022-08-04 14:00 UTC, Niraj-Kamdar commented on packages/py/core/src/uri_resolution/resolvers/extendable/uri_resolver_wrapper.py
> +    if not data or (not data.get("uri") and not data.get("manifest")):
this just doesn't look readable, how about?
```
 not(data and (data.get("uri") or data.get("manifest)))
 ```

2022-08-04 14:00 UTC, Niraj-Kamdar commented on packages/py/core/src/uri_resolution/resolvers/plugin/plugin_resolver.py
> +            print(f'what is it {self.create_plugin_api}')
remove debug leftover

2022-08-04 14:00 UTC, Niraj-Kamdar commented on packages/py/core/src/uri_resolution/resolvers/get_env_from_uri_or_resolution.py
> +) -> Union[Env, None]:
should be Optional[Env] instead

2022-08-04 14:00 UTC, Niraj-Kamdar commented on packages/py/core/src/manifest/formats/web3api/deserialize.py
> +from .prealpha_0_0_1_9 import Web3ApiManifest
Shouldn't we use same pattern that we use for generating manifest for js using jsonschema here?

2022-08-04 14:00 UTC, Niraj-Kamdar commented on packages/py/core/src/tests/test_get_implementations_spec.py
> +def test_works_complex_redirects():
Shouldn't this restructured as pytest paramaterize

2022-08-18 16:36 UTC, cbrzn commented
hey @Niraj-Kamdar it's ok if we put this on draft?

2022-09-14 07:48 UTC, cbrzn commented
Closing this because we are going to execute this on #1232

2022-09-14 07:48 UTC, closed without merging