generate bindings for workflow script
Web3-API/prototype pull request #1100
Opened 2022-08-09 07:04 UTC by fetsorn

Resolves #970.

2022-08-09 13:59 UTC, cbrzn reviewed
I think it would make sense not to create a new package for the workflow manifest but rather, to add it to the `wrap` manifests (will live along with Abi). Since IIRC we are making the workflow a part of the WRAP protocol

2022-08-10 13:45 UTC, Niraj-Kamdar requested changes
LGTM once the requested changes are addressed

2022-08-10 13:45 UTC, Niraj-Kamdar commented on packages/manifests/workflow/formats/workflow/0.1.json
> +  "required": ["format", "name", "jobs"],
Remove redundant properties

2022-08-10 13:45 UTC, Niraj-Kamdar commented on packages/js/manifests/workflow/src/formats/workflow/index.ts
> +  PolywrapWorkflow as PolywrapWorkflow_0_1
Add PolywrapJobs here as we discussed and export it from here

2022-08-10 13:45 UTC, Niraj-Kamdar commented on packages/js/manifests/workflow/src/index.ts
> +export { Jobs } from "./formats/workflow/0.1"
Instead of this, it should be exported from the formats

2022-08-10 13:45 UTC, Niraj-Kamdar commented on packages/js/manifests/workflow/README.md
> +# @polywrap/polywrap-manifest-types-js
this should be `workflow-manifest-types-js`

2022-08-10 13:45 UTC, Niraj-Kamdar commented on packages/js/manifests/workflow/package.json
> +  "description": "Polywrap Manifest TypeScript Typings",
Polywrap -> Workflow

2022-08-15 12:07 UTC, Niraj-Kamdar submitted a review, later dismissed

2022-08-22 11:52 UTC, Niraj-Kamdar commented
@fetsorn Can you fix the conflicts so we can get this merged and then would be able to merge the `polywrap.test.yaml` PR.

2022-08-23 09:02 UTC, Niraj-Kamdar submitted a review, later dismissed

2022-08-27 16:19 UTC, merged