replace Option with Box | null in wasm-as
Web3-API/prototype pull request #1154
Opened 2022-08-17 14:53 UTC by fetsorn

resolves #1132

2022-08-23 12:22 UTC, krisbitney requested changes
I'm working on debugging it but there seems to be an issue. 

First, I misspoke when I was saying templates might not build/test correctly. I was talking about their usage in the CLI create command, which downloads the templates from npm. The `@polywrap/templates` package itself should build and pass tests. Sorry about that.

So onto the problem: the Box type is not exported from `@polywrap/wasm-as`. You might think "of course it is!". I've been looking in it and I would agree that you are exporting it. Everything looks correct. I've even tried adding another export statement at the top level `index.ts` file and I get a build error when I do. I'm not sure why, but the type does not appear in `packages/wasm/as/build/index.d.ts`.

I'm still working on finding the issue but I wanted to update you.

2022-08-25 15:30 UTC, krisbitney commented
The AssemblyScript templates do pass tests once we add this to `polywrap.build.yaml`:

```
linked_packages:
  - name: "@polywrap/wasm-as"
    path: ../../../wasm/as
```

2022-09-07 01:04 UTC, dOrgJelli submitted a review, later dismissed

2022-09-07 01:45 UTC, dOrgJelli approved these changes

2022-09-07 02:05 UTC, merged