fix: interface module bindings
Web3-API/prototype pull request #1219
Opened 2022-09-08 11:27 UTC by Niraj-Kamdar

2022-09-08 17:16 UTC, cbrzn reviewed
Thanks for pushing this 🙏 Probably I am wrong and please correct me if so, but I think this adds the capability of interface invocation, hence, we should add the `interface-invoke` test cases (as in https://github.com/polywrap/toolchain/tree/origin/packages/test-cases/cases/wrappers/wasm-as/interface-invoke)

2022-09-08 19:24 UTC, Niraj-Kamdar commented
@cbrzn I agree, the tests should cover this scenario

2022-09-12 11:37 UTC, krisbitney requested changes

2022-09-12 11:37 UTC, krisbitney commented on packages/js/client/src/__tests__/e2e/wasm-as.spec.ts
> +    const implementationPath = `${GetPathToTestWrappers()}/wasm-rs/implementations/test-wrapper`;
It looks like there is a typo here. The wrapper URIs point to the `wasm-rs` folder, but they should point to `wasm-as`.

2022-09-13 07:31 UTC, krisbitney approved these changes

2022-09-13 10:30 UTC, cbrzn approved these changes

2022-09-13 10:31 UTC, merged