fix(schema-bind): handle reserved keywords for serde in rust
Web3-API/prototype pull request #1220
Opened 2022-09-08 13:15 UTC by Niraj-Kamdar

2022-09-09 04:19 UTC, cbrzn reviewed
Would it make sense to add a test in the `test-cases/cases/wasm/wasm-rs/json-type` folder to ensure this works?

2022-09-10 20:51 UTC, cbrzn commented on packages/js/client/src/__tests__/e2e/test-cases.ts
> +  if (testReserved) {
If this is added, then the `wasm-rs` file should be edited to pass `true` for this arg when calling the `runJsonTypeTest` function

2022-09-12 11:07 UTC, dOrgJelli requested changes
LGTM!

2022-09-12 11:07 UTC, dOrgJelli commented on packages/js/client/src/__tests__/e2e/test-cases.ts
> +export const runJsonTypeTest = async (client: PolywrapClient, uri: string, testReserved: boolean = false) => {
Can you please pass in `true` for `testReserved` in the wasm-rs tests? This logic is not currently being used.

2022-09-13 10:31 UTC, cbrzn approved these changes

2022-09-15 19:01 UTC, dOrgJelli approved these changes

2022-09-15 19:01 UTC, merged