Added setup guide
Web3-API/prototype pull request #1240
Opened 2022-09-19 05:53 UTC by OmPals

- Added a setup guide for building and testing the core package.

2022-09-19 10:14 UTC, Niraj-Kamdar requested changes

2022-09-19 10:14 UTC, Niraj-Kamdar commented on packages/py/core/README.md
> +```
Check this out: https://python-poetry.org/docs/#installation

You don't need to install poetry on venv, you can directly install it globally which would be handier for packages that support multiple python versions.

2022-09-19 10:14 UTC, Niraj-Kamdar commented on packages/py/core/README.md
> +- Now we are ready to build and test the core package using Poetry and PyTest.
For building package use: `poetry build`, for testing `poetry run pytest`

2022-10-17 05:58 UTC, cbrzn commented
Closing this PR because now we have https://github.com/polywrap/python-client

2022-10-17 05:58 UTC, closed without merging