CLI - rename `run` to `test`
Web3-API/prototype pull request #1348
Opened 2022-10-19 16:19 UTC by pileks

This PR renames the `run` CLI command to `test`.

In addition, there are some changes to the language around the `test` command to make it more uniform with the new name.

2022-10-19 16:50 UTC, Niraj-Kamdar submitted a review, later dismissed
LGTM! Thanks for tackling this!

2022-10-19 16:51 UTC, Niraj-Kamdar commented
Can you also rename file names from `run.ts` and `run.spec.ts` to test one

2022-10-19 17:00 UTC, Niraj-Kamdar requested changes

2022-10-19 17:00 UTC, Niraj-Kamdar commented on packages/cli/src/__tests__/e2e/help.spec.ts
> +  test|t [options]             Execute Test Manifests
Instead of execute test manifest, it's better to have it as execute tests

2022-10-19 17:00 UTC, Niraj-Kamdar commented on packages/cli/lang/en.json
> +  "commands_run_description": "Execute Test Manifests",
Execute Tests

2022-10-20 12:21 UTC, Niraj-Kamdar approved these changes, later dismissed

2022-10-25 15:48 UTC, Niraj-Kamdar approved these changes

2022-10-25 15:49 UTC, cbrzn approved these changes

2022-10-26 09:02 UTC, dOrgJelli approved these changes

2022-10-26 09:03 UTC, merged