Pileks/feat/cli separate build codegen actions
Web3-API/prototype pull request #1385
Opened 2022-11-03 17:32 UTC by pileks

2022-12-14 08:04 UTC, Niraj-Kamdar approved these changes, later dismissed
LGTM!

2022-12-20 13:28 UTC, krisbitney requested changes
LGTM! 

I left a couple of comments with questions. Let me know what you think. Maybe no changes are needed.

2022-12-20 13:28 UTC, krisbitney commented on packages/cli/src/commands/build.ts
>      await execute();
Is `execute` called twice in this branch? On line 308 and in the watcher?

2022-12-20 13:28 UTC, krisbitney commented on packages/cli/src/commands/build.ts
> +    return;
Should we return an exit code here?

2022-12-20 17:59 UTC, pileks commented on packages/cli/src/commands/build.ts
> +    return;
...and print an error, yes!

2022-12-20 17:59 UTC, pileks commented on packages/cli/src/commands/build.ts
>      await execute();
Yes it is!

We execute once first, then set up the watcher, as the watcher only triggers on changes in watched files.

2022-12-20 18:01 UTC, krisbitney commented on packages/cli/src/commands/build.ts
>      await execute();
Okay, right, understood!

2022-12-20 18:01 UTC, krisbitney approved these changes, later dismissed

2022-12-30 10:55 UTC, krisbitney commented
Can this be merged @pileks @dOrgJelli ?

2023-01-02 20:06 UTC, pileks commented
@krisbitney From a standpoint of implementation - Yes, it's just a matter of being reviewed! 😄

2023-01-03 06:06 UTC, krisbitney approved these changes, later dismissed

2023-01-03 06:15 UTC, dOrgJelli requested changes

2023-01-03 06:15 UTC, dOrgJelli commented on packages/cli/lang/en.json
> +  "commands_build_error_codegen_failed": "Code generation failed!",
NIT: I don't think we need to add exclamations (`!`) to output messages, I don't believe we do this elsewhere.

2023-01-03 06:15 UTC, dOrgJelli commented on packages/cli/src/commands/build.ts
> +  } else if (isPluginManifestLanguage(language)) {
I think that we should be handling this inside of the "Compiler", like we already do for interface projects. I'll make a push now to add this.

2023-01-03 06:52 UTC, dOrgJelli commented on packages/cli/lang/en.json
> +  "commands_build_error_codegen_failed": "Code generation failed!",
Made these changes here: https://github.com/polywrap/toolchain/pull/1467

2023-01-03 06:52 UTC, dOrgJelli commented on packages/cli/src/commands/build.ts
> +  } else if (isPluginManifestLanguage(language)) {
Made these changes here: https://github.com/polywrap/toolchain/pull/1467

2023-01-03 06:54 UTC, dOrgJelli requested changes
Also @pileks we should update the CLI's README.

2023-01-03 14:19 UTC, pileks commented on packages/cli/lang/en.json
> +  "commands_build_error_codegen_failed": "Code generation failed!",
Thanks for the PR, merged.

2023-01-03 16:16 UTC, pileks commented
@dOrgJelli I've performed the minimal required changes to the readme just now.

We can refactor the readme to use `doc-snippets` in a later PR - for now this should be it.

LMK if this works.

2023-01-03 20:49 UTC, dOrgJelli approved these changes

2023-01-03 20:49 UTC, merged