fix: build vm strategy for the arm machine
Web3-API/prototype pull request #1485
Opened 2023-01-17 21:29 UTC by Niraj-Kamdar

- Closes: #1397

## Changelog
- feat: docker image uses alpine linux as base image
- fix: VM build strategy now uses image with appropriate architecture to build the wrapper

2023-01-18 06:16 UTC, dOrgJelli approved these changes, later dismissed
LGTM!

2023-01-18 10:47 UTC, krisbitney requested changes
I still get this:
<img width="1391" alt="Screenshot 2023-01-18 at 4 10 14 PM" src="https://user-images.githubusercontent.com/39842820/213152116-47a309bf-eda3-40aa-88a6-2cfe93c4bdfa.png">

2023-01-18 13:14 UTC, cbrzn submitted a review, later dismissed
edit: Niraj fixed the latest version in docker so we good :-)

2023-01-18 15:07 UTC, krisbitney approved these changes

2023-01-18 15:15 UTC, Niraj-Kamdar commented
> I still get this: <img alt="Screenshot 2023-01-18 at 4 10 14 PM" width="1391" src="https://user-images.githubusercontent.com/39842820/213152116-47a309bf-eda3-40aa-88a6-2cfe93c4bdfa.png">

Turned out this was the issue on @krisbitney side so all good

2023-01-18 16:56 UTC, dOrgJelli approved these changes

2023-01-18 16:56 UTC, merged

2023-01-24 00:14 UTC, dOrgJelli commented on packages/cli/src/lib/defaults/build-strategies/wasm/rust/vm/Dockerfile
> +RUN apk add curl build-base pkgconfig openssl-dev bash
Hey @Niraj-Kamdar, apologies for not asking about this before, but why are we now installing `build-base`, `pkgconfig`, `openssl-dev` and `base`?

Also I should have caught this before, but for rust builds we require `clang`, `llvm` and `build-essentials` to build & link native C libs.

2023-01-24 00:16 UTC, dOrgJelli commented on packages/cli/src/lib/defaults/build-strategies/wasm/rust/image/Dockerfile.mustache
> +FROM rust:1.66-alpine as base
Also what is the reasoning for moving to alpine?

2023-01-24 00:17 UTC, dOrgJelli commented on packages/cli/src/lib/defaults/build-strategies/wasm/rust/vm/Dockerfile
> +RUN apk add curl build-base pkgconfig openssl-dev bash
One answer I found is that `build-base` is the alpine equivalent of `build-essentials`.