cli/create: remove node & react from supported langs in app template
Web3-API/prototype pull request #1525
Opened 2023-02-07 15:53 UTC by cbrzn

in a previous PR the `typescript-node` and `typescript-react` templates have been removed from `app` (https://github.com/polywrap/toolchain/pull/1500); this aims to update the create command with these changes.

the ci did not catch this because we're directly downloading the latest version from npm (0.9.4) when running the create command. this makes me think that decoupling templates from toolchain might be a necessary thing to do sooner than later (so these things don't go to production without us noticing)

2023-02-08 07:02 UTC, krisbitney requested changes
This is a great PR. Thanks looking at this.

There seems to be a bug where the full template isn't generated:

<img width="1440" alt="Screenshot 2023-02-08 at 12 27 04 PM" src="https://user-images.githubusercontent.com/39842820/217457551-080b538b-04cf-4b84-aa51-0ec021387116.png">

2023-02-08 07:05 UTC, krisbitney commented
Maybe the PR is fine as is and we should merge it assuming it will work when 0.10.0 is released. We can do a patch fix if there are problems. What do you think?

2023-02-08 11:31 UTC, cbrzn commented
> Maybe the PR is fine as is and we should merge it assuming it will work when 0.10.0 is released. We can do a patch fix if there are problems. What do you think?

@krisbitney yes, that's the exact reason - actually, it amazes me that the CI went green (I was expecting it to fail lol). but yah, I feel comfortable with merging this so we're ready for 0.10 release

2023-02-09 07:03 UTC, krisbitney approved these changes

2023-02-11 01:50 UTC, dOrgJelli approved these changes

2023-02-11 01:50 UTC, merged