Pileks/feat/js client config unique maps
Web3-API/prototype pull request #1557
Opened 2023-02-16 17:46 UTC by pileks

**Early WIP, comment on approach if you feel strongly about what you see**

2023-03-01 13:15 UTC, krisbitney approved these changes, later dismissed
Everything looks good. This is well done! The use of objects instead of arrays looks really clean.

Before merging, I think the question about using `string` vs. `Uri` should be resolved, just because of the recent decision to use `Uri` in the core.

I think making the implementations array of type `Uri[]` instead of `string[]` makes sense.

2023-03-02 06:45 UTC, dOrgJelli requested changes

2023-03-02 06:45 UTC, dOrgJelli commented on packages/js/client/src/__tests__/e2e.spec.ts
> -    typeTestCases(i);
Oops, need to revert this

2023-03-02 06:45 UTC, dOrgJelli commented on packages/js/core/src/types/CoreClient.ts
> -  getInterfaces(): readonly InterfaceImplementations[] | undefined;
I noticed some inconsistencies in this file when it comes to `readonly` and `ReadOnly<...>` usage. Could we please use it the same in all methods / properties? If I'm missing some nuances please inform :)

2023-03-02 17:41 UTC, nerfZael requested changes

2023-03-02 17:41 UTC, nerfZael commented on packages/js/core-client/src/PolywrapCoreClient.ts
> +    return envs[uri.uri];
This will probably treat "wrap://ens/" and "ens/" as different URIs

2023-03-02 17:41 UTC, nerfZael commented on packages/js/core-client/src/PolywrapCoreClient.ts
> +    return envs[uri.uri];
We could maybe sanitize this stuff in the constructor

2023-03-07 16:51 UTC, closed without merging