Dev guidelines
Web3-API/prototype pull request #330
Opened 2021-05-11 20:57 UTC by morrigan

Something that has been in draft for some time now but seems like the right moment to make things official :)

cc @diegobarboza1

Included also mentioned branch changes from #325
Closing #63

2021-10-13 18:37 UTC, cbrzn submitted a review, later dismissed
LGTM 🍏

2021-11-29 07:49 UTC, Niraj-Kamdar requested changes

2021-11-29 07:49 UTC, Niraj-Kamdar commented on DEV_GUIDELINES.md
> +Github projects are created for each project where there is always one active project board for core development i.e. [Prealpha board](https://github.com/polywrap/monorepo/projects/1) and others for
Since we have moved integrations in the separate https://github.com/polywrap/integrations repo we can have project boards for integrations there.

2021-12-08 01:27 UTC, dOrgJelli approved these changes

2021-12-08 01:28 UTC, merged