Update wording of monorepo README and update to Polywrap brand
Web3-API/prototype pull request #407
Opened 2021-07-11 05:24 UTC by kev-ngo

2021-10-13 19:05 UTC, cbrzn submitted a review, later dismissed
LGTM 🍏

2021-11-30 09:20 UTC, Niraj-Kamdar requested changes
There is a minor typo

2021-11-30 09:20 UTC, Niraj-Kamdar commented on README.md
> +yarn lint: fix
```suggest
yarn lint:fix
```

2021-12-08 00:59 UTC, dOrgJelli approved these changes

2021-12-08 00:59 UTC, merged

2021-12-08 01:00 UTC, dOrgJelli commented on README.md
> +yarn lint: fix
Shoot, missed this, will fix in prealpha-dev. Nice catch!