Feat: Multisend wrapper
Web3-API/prototype pull request #500
Opened 2021-10-08 18:14 UTC by cbrzn

2021-12-14 07:32 UTC, Niraj-Kamdar requested changes
We should move this to integrations repo.

2021-12-14 07:32 UTC, Niraj-Kamdar commented on packages/apis/multisend/scripts/createPayload.js
> +const fs = require("fs");
What's the use of these scripts? If it's for just testing then we should create jest tests instead

2021-12-14 07:32 UTC, Niraj-Kamdar commented on packages/apis/multisend/deploy/00_delegator.js
> +  const { deploy } = deployments;
Let's use typescript here.

2022-05-23 06:09 UTC, cbrzn commented
> We should move this to integrations repo.

Hey @Niraj-Kamdar I totally agree with you - Currently, this wrapper is not working as expected because it only works with Contract Accounts and not with EOAs (because of the `msg.sender`). I will update this and use instead the multicall library (In the integrations repository)

2022-05-23 12:49 UTC, dOrgJelli commented
Closing this for now @cbrzn

2022-05-23 12:49 UTC, closed without merging