664 | ref (core & schema): use string `.substr` method
Web3-API/prototype pull request #672
Opened 2022-02-08 22:57 UTC by arcbjorn

2022-02-09 07:28 UTC, Niraj-Kamdar requested changes

2022-02-09 07:28 UTC, Niraj-Kamdar commented on packages/schema/bind/src/bindings/wasm-as/functions.ts
> +      if (nullType.substring(-nullOptional.length) === nullOptional) {
AFAIK, This won't work and should be refactored with `endsWith` anyway.
```
if (nullType.endsWith(nullOptional))
```

2022-02-09 07:28 UTC, Niraj-Kamdar commented on packages/schema/parse/src/extract/imported-types-utils.ts
> +  const queryTest = typeName.substring(-queryIdentifier.length);
Same here can be refactored with `endsWith` syntax

2022-02-10 08:42 UTC, Niraj-Kamdar approved these changes

2022-02-13 11:21 UTC, dOrgJelli approved these changes

2022-02-13 11:21 UTC, merged