Filesystem plugin separation of concerns
Web3-API/prototype pull request #912
Opened 2022-06-10 23:36 UTC by pileks

Partially closes #622 and #714 (filesystem part)

After discussion with @nerfZael the following was done:
- Introduced an interface for `filesystem`-like plugins
- Extracted `uri-resolver` interface implementation from `filesystem` plugin into its own `fs-uri-resolver` plugin
- Implemented basic `filesystem` plugin which implements the `filesystem` interface
- Introduced a new build command for interfaces that follow the `@web3api/*-interface` pattern and added it to the main build command

Advice/feedback would be much appreciated!

2022-06-11 18:18 UTC, nerfZael requested changes

2022-06-11 18:18 UTC, nerfZael commented on packages/core-interfaces/filesystem/package.json
> +    "deploy": "npx w3 build --ipfs http://localhost:5001"
there's no --ipfs option of the build command anymore. You can replace this with `npx w3 deploy`

2022-06-11 18:18 UTC, nerfZael commented on packages/core-interfaces/filesystem/src/mutation.graphql
> +  rm(path: String!): Boolean
we should add optional options for `recursive` and `force`

2022-06-11 18:18 UTC, nerfZael commented on packages/core-interfaces/filesystem/src/mutation.graphql
> +  mkdir(path: String!): Boolean
we should add optional options for `recursive`

2022-06-11 18:18 UTC, nerfZael commented on packages/js/plugins/filesystem/src/mutation/index.ts
> +    fs.writeFileSync(input.path, Buffer.from(input.data));
Even though the call on the wrapper side is blocking, this part happens client-side and could be awaited to give other client-side tasks more processing time. E.g you can use:
```typescript
import { promises as fsPromises } from 'fs';
await fsPromises.writeFile('file.txt', 'data');
```

2022-06-11 18:18 UTC, nerfZael commented on packages/js/plugins/filesystem/src/mutation/index.ts
> +    fs.writeFileSync(input.path, Buffer.from(input.data));
Same applies to all other functions ofc

2022-06-11 18:18 UTC, nerfZael commented on packages/js/plugins/filesystem/src/mutation/index.ts
> +    return true;
If we're returning a boolean instead of void, we might as well catch the error and return false in that case

2022-06-11 18:18 UTC, nerfZael commented on packages/js/plugins/filesystem/src/query/index.ts
> +    // TODO: Maybe check if input.encoding is within supported encodings?
Maybe use an enum instead of string for encoding?

2022-06-11 18:18 UTC, nerfZael commented on packages/js/plugins/filesystem/src/query/index.ts
> +    return fs.promises.readFile(input.path);
Oh, here you ARE using promises :D

2022-06-11 18:18 UTC, nerfZael commented on packages/js/plugins/filesystem/src/__tests__/e2e.spec.ts
> +    const fsReadFileAsStringResult = await Filesystem_Query.readFileAsString(
This might be a bit too verbose a name for the only "result" in this test case. Personally, I'd rather just use `result`. What do you think?

2022-06-11 18:18 UTC, nerfZael commented on packages/js/plugins/filesystem/src/__tests__/e2e.spec.ts
> +  it("should write data to a file and succesfully remove it", async () => {
I think it'd be better to have a test case per wrapper method. So, separating writing and removing. This is even more important once you add rm options

2022-06-11 18:18 UTC, nerfZael commented on packages/js/plugins/uri-resolvers/filesystem-resolver/src/query/index.ts
> +    if (input.authority !== "fs") {
@dOrgJelli Should we start renaming `fs` authority to `file` ?

2022-06-11 18:18 UTC, nerfZael commented on packages/js/plugins/uri-resolvers/filesystem-resolver/src/query/index.ts
> +        } catch (e) {
We need better error handling, but I know you just re-implemented what was here originally. We can leave this as is since there's a PR up to improve resolver error handling and it's on my TODO list to get that implemented soon

2022-06-13 19:50 UTC, nerfZael commented on packages/js/plugins/filesystem/src/mutation/index.ts
> +    return true;
After a call with @pileks we decided it'd be better to just let the plugin throw so that the app can catch the error instead of masking it

2022-06-22 22:40 UTC, nerfZael requested changes

2022-06-22 22:40 UTC, nerfZael commented on packages/core-interfaces/filesystem/package.json
> +    "deploy": "npx polywrap build --ipfs http://localhost:5001"
`npx polywrap deploy`

2022-06-22 22:40 UTC, nerfZael commented on packages/js/plugins/uri-resolvers/filesystem-resolver/src/index.ts
> +    if (input.authority !== "fs") {
After talking with @dOrgJelli we decided to cover both `fs` and `file` authorities

2022-06-22 22:40 UTC, nerfZael commented on packages/js/plugins/uri-resolvers/filesystem-resolver/src/index.ts
> +      "polywrap.json",
Only "polywrap.json" is currently valid in the build artifacts, you can remove others

2022-06-22 22:40 UTC, nerfZael commented on packages/js/plugins/uri-resolvers/filesystem-resolver/src/__tests__/e2e.spec.ts
> +        // IPFS is required for downloading Web3API packages
You can remove these comments

2022-06-22 22:40 UTC, nerfZael commented on packages/js/plugins/filesystem/src/utils/encodingUtils.ts
> +    case "ASCII":
This can be a string?

2022-06-22 22:40 UTC, nerfZael commented on packages/js/plugins/filesystem/src/utils/encodingUtils.ts
> +export const filesystemEncodingToBufferEncoding = (
I'd name this file after this function: `filesystemEncodingToBufferEncoding.ts`

2022-06-22 22:40 UTC, nerfZael commented on packages/js/plugins/filesystem/src/__tests__/e2e.spec.ts
> +      await fs.promises.rm(tempFilePath, { force: true, recursive: true });
What does recursive do when deleting a file?

2022-06-22 22:40 UTC, nerfZael commented on packages/js/plugins/filesystem/src/__tests__/e2e.spec.ts
> +  it("should read a file", async () => {
`can read a file` or `should be able to read a file`
I prefer the first one

2022-06-22 22:40 UTC, nerfZael commented on packages/js/plugins/filesystem/src/__tests__/e2e.spec.ts
> +    const nonExistentFilePath = `${sampleFilePath}nonexistent`;
Maybe just `nonexistent` without the ${sampleFilePath} prefix ?

2022-06-22 22:40 UTC, nerfZael commented on packages/js/plugins/filesystem/src/__tests__/e2e.spec.ts
> +      await fs.promises.rm(tempFilePath, { force: true, recursive: true });
You could just delete the whole sample dir and create needed files when a test needs them

2022-06-22 22:40 UTC, nerfZael commented on packages/js/plugins/filesystem/src/__tests__/e2e.spec.ts
> +  it("should create a folder recursively", async () => {
Either use dirs everywhere or folders when naming
I prefer directory

2022-06-22 22:40 UTC, nerfZael commented on packages/js/plugins/filesystem/src/__tests__/e2e.spec.ts
> +  it("should remove a file recursively", async () => {
Don't you mean  `remove a directory recursively` ?

2022-06-22 22:40 UTC, nerfZael commented on packages/js/plugins/filesystem/src/__tests__/e2e.spec.ts
> +      await fs.promises.rm(tempFilePath, { force: true, recursive: true });
I'd also add this removal logic in beforeAll in case someone kills the test process in the middle of execution

2022-06-22 22:42 UTC, nerfZael commented
After talking with @dOrgJelli we decided file system should be two words, so: `FileSystem`, fileSystem`, `file-system` etc

2022-06-23 09:45 UTC, pileks commented on packages/js/plugins/filesystem/src/__tests__/e2e.spec.ts
> +    const fsReadFileAsStringResult = await Filesystem_Query.readFileAsString(
I agree that, especially when there is only one result object in the test, we can name it `result`.
I'd still keep `xResult` when there are more results being loaded - not a fan of reusing variables.
Thoughts?

2022-06-23 09:45 UTC, pileks commented on packages/js/plugins/filesystem/src/__tests__/e2e.spec.ts
> +  it("should write data to a file and succesfully remove it", async () => {
Makes sense. Then we'd use `fs` to create the folder/file being removed.

2022-06-23 09:45 UTC, pileks commented on packages/js/plugins/filesystem/src/mutation/index.ts
> +    return true;
I'd lean on throwing an error and not returning anything in that case.

2022-06-23 09:45 UTC, pileks commented on packages/js/plugins/uri-resolvers/filesystem-resolver/src/query/index.ts
> +    if (input.authority !== "fs") {
If I have a vote in this, I'd go with doing that as part of a separate issue simply to keep the scope of the PR at a manageable level.

2022-06-23 09:45 UTC, pileks commented on packages/core-interfaces/filesystem/src/schema.graphql
> +  readFileAsString(path: String!, encoding: Encoding): String!
@nerfZael commented that @dOrgJelli mentioned in the IPFS PR that we should leave decoding to the consumer of the plugin (remove any `asString` stuff).
Should we also remove `readFileAsString` from here in favor of the same approach?
This would also mean significantly simplifying the interface, as we would not need to have the `Encoding` enum below.

2022-06-23 09:45 UTC, pileks commented on packages/js/plugins/uri-resolvers/filesystem-resolver/src/__tests__/e2e.spec.ts
> +        // IPFS is required for downloading Web3API packages
I'd only delete these in the setup phase - the ones in the actual test seem useful enough.

2022-06-23 09:45 UTC, pileks commented on packages/js/plugins/filesystem/src/utils/encodingUtils.ts
> +    case "ASCII":
AFAIK, Enums in wrappers are actually of type `Something_Enum | Something_EnumString`:
This is the otuput in `types.ts` for an enum:
```javascript
export enum Filesystem_EncodingEnum {
  ASCII,
  UTF8,
  UTF16LE,
  UCS2,
  BASE64,
  BASE64URL,
  LATIN1,
  BINARY,
  HEX,
}

export type Filesystem_EncodingString =
  | "ASCII"
  | "UTF8"
  | "UTF16LE"
  | "UCS2"
  | "BASE64"
  | "BASE64URL"
  | "LATIN1"
  | "BINARY"
  | "HEX"

export type Filesystem_Encoding = Filesystem_EncodingEnum | Filesystem_EncodingString;
```

2022-06-23 09:45 UTC, pileks commented on packages/js/plugins/filesystem/src/utils/encodingUtils.ts
> +export const filesystemEncodingToBufferEncoding = (
Would we then want to `export default`?

2022-06-23 09:45 UTC, pileks commented on packages/js/plugins/filesystem/src/__tests__/e2e.spec.ts
> +      await fs.promises.rm(tempFilePath, { force: true, recursive: true });
Nothing, really. Copy-paste :grin:

2022-06-23 18:47 UTC, nerfZael commented on packages/js/plugins/uri-resolvers/filesystem-resolver/src/query/index.ts
> +    if (input.authority !== "fs") {
After talking with @dOrgJelli  we decided to support both

2022-06-23 21:54 UTC, nerfZael approved these changes, later dismissed

2022-06-24 07:52 UTC, dOrgJelli approved these changes, later dismissed

2022-06-24 08:15 UTC, merged