Added Tezos Infra Module
Web3-API/prototype pull request #922
Opened 2022-06-15 19:51 UTC by namesty

Closes polywrap/integrations#52

This PR adds a Tezos blockchain environment, as a default infra module

2022-06-19 04:40 UTC, dOrgJelli requested changes

2022-06-19 04:40 UTC, dOrgJelli commented on packages/cli/src/lib/defaults/infra-modules/tezos/cmds.js
> +const CMDS = {
@namesty I'm confused by how these js modules get used, as I don't see them referenced in the docker-compose.yaml or Dockerfile.

Are they useful to users in some way? If so, how can they access them? Is this something common you think we should do (bundle helper scripts w/ the infra modules)?

2022-06-22 20:15 UTC, namesty commented on packages/cli/src/lib/defaults/infra-modules/tezos/cmds.js
> +const CMDS = {
Yes, they do seem unrelated, I'll remove them

2022-06-23 10:26 UTC, Niraj-Kamdar reviewed
Do tezos have test-env-js like we have for default test-env?

This will be out of scope for this PR but would like to suggest that we should have better way to check whether all the services are started or stopped instead of sleeping for arbitrary time and hope it will be started

2023-03-02 07:03 UTC, dOrgJelli commented
Going to close this inactivity. Additionally we should publish this within another repo instead of adding it as a baked-in default within the CLI.

2023-03-02 07:03 UTC, closed without merging